// Test the predict endpoint

POST http://54.236.180.248:30081/predict
Content-Type: application/json

{
  // No request body needed as the server fetches CPU data internally
}

###

// Test the predict-terraform endpoint
POST http://54.236.180.248:30081/predict-terraform
Content-Type: application/json

{
  // No request body needed as the server fetches CPU data internally
}
